export enum OperationAction {
  BlogArticleCreate = 'blog.article.create',
  BlogArticleDelete = 'blog.article.delete',
  BlogArticlePublish = 'blog.article.publish',
  BlogArticleTagsUpdate = 'blog.article.tags.update',
  BlogArticleUpdate = 'blog.article.update',
  BlogLikeBatchDelete = 'blog.like.batch-delete',
  BlogLikeDelete = 'blog.like.delete',
  BlogTagCreate = 'blog.tag.create',
  BlogTagDelete = 'blog.tag.delete',
  BlogTagUpdate = 'blog.tag.update',
  FileDelete = 'file.delete',
  FileUpload = 'file.upload',
  MenuCreate = 'menu.create',
  MenuDelete = 'menu.delete',
  MenuUpdate = 'menu.update',
  ModuleCreate = 'module.create',
  ModuleDelete = 'module.delete',
  ModuleUpdate = 'module.update',
  ProfileChangePassword = 'profile.change-password',
  ProfileUpdate = 'profile.update',
  RoleAssignAccess = 'role.assign-access',
  RoleAssignUser = 'role.assign-user',
  RoleCreate = 'role.create',
  RoleDelete = 'role.delete',
  RoleUpdate = 'role.update',
  UserAssignRole = 'user.assign-role',
  UserCreate = 'user.create',
  UserDelete = 'user.delete',
  UserResetPassword = 'user.reset-password',
  UserUpdate = 'user.update',
}

const operationActionLabels: Record<OperationAction, string> = {
  [OperationAction.BlogArticleCreate]: '新建文章',
  [OperationAction.BlogArticleDelete]: '删除文章',
  [OperationAction.BlogArticlePublish]: '发布文章',
  [OperationAction.BlogArticleTagsUpdate]: '更新文章标签',
  [OperationAction.BlogArticleUpdate]: '更新文章',
  [OperationAction.BlogLikeBatchDelete]: '批量删除喜欢记录',
  [OperationAction.BlogLikeDelete]: '删除喜欢记录',
  [OperationAction.BlogTagCreate]: '新建标签',
  [OperationAction.BlogTagDelete]: '删除标签',
  [OperationAction.BlogTagUpdate]: '更新标签',
  [OperationAction.FileDelete]: '删除文件',
  [OperationAction.FileUpload]: '上传文件',
  [OperationAction.MenuCreate]: '新建菜单',
  [OperationAction.MenuDelete]: '删除菜单',
  [OperationAction.MenuUpdate]: '更新菜单',
  [OperationAction.ModuleCreate]: '新建模块',
  [OperationAction.ModuleDelete]: '删除模块',
  [OperationAction.ModuleUpdate]: '更新模块',
  [OperationAction.ProfileChangePassword]: '修改登录密码',
  [OperationAction.ProfileUpdate]: '更新个人资料',
  [OperationAction.RoleAssignAccess]: '调整角色权限',
  [OperationAction.RoleAssignUser]: '调整角色成员',
  [OperationAction.RoleCreate]: '新建角色',
  [OperationAction.RoleDelete]: '删除角色',
  [OperationAction.RoleUpdate]: '更新角色',
  [OperationAction.UserAssignRole]: '调整用户角色',
  [OperationAction.UserCreate]: '新建用户',
  [OperationAction.UserDelete]: '删除用户',
  [OperationAction.UserResetPassword]: '重置用户密码',
  [OperationAction.UserUpdate]: '更新用户',
};

export function getOperationActionLabel(action: string) {
  return operationActionLabels[action as OperationAction] ?? action;
}
