export {
  appModuleCreateInputSchema as appModuleSchema,
  appModuleUpdateInputSchema as appModuleUpdateSchema,
  assignRolesInputSchema as assignRolesSchema,
  assignUsersInputSchema as assignUsersSchema,
  changePasswordInputSchema as changePasswordSchema,
  menuCreateInputSchema as menuSchema,
  menuUpdateInputSchema as menuUpdateSchema,
  profileUpdateInputSchema as profileSchema,
  resetPasswordInputSchema as resetPasswordSchema,
  roleCreateInputSchema as roleSchema,
  roleAccessUpdateInputSchema,
  roleAccessUpdateInputSchema as assignAccessSchema,
  roleAccessUpdateInputSchema as roleAccessSchema,
  roleUpdateInputSchema as roleUpdateSchema,
  userCreateInputSchema as userCreateSchema,
  userUpdateInputSchema as userUpdateSchema,
} from '@veb/api-contracts';
